name-template: "🚀 Release v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "refactor"
      - "cleanup"
  - title: "📚 Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "⚙️ Dependencies"
    labels:
      - "dependencies"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"

template: |
  ## 📦 What's Changed
  $CHANGES

  ## 🙌 Contributors
  $CONTRIBUTORS

version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "bug"
      - "fix"
      - "chore"
      - "refactor"
      - "docs"
      - "dependencies"

replacers:
  - search: '/(fix|feat|docs|chore|refactor|test)(\(.*\))?:\s*/'
    replace: ""

exclude-labels:
  - "skip-changelog"

tag-resolver:
  method: semver
