theme: jekyll-theme-cayman
title: logkey
description: A lightweight Python application to log user inputs into a CSV file with Docker support for easy deployment and GitHub Actions to automate key workflows.
show_downloads: true
