name: Create and publish a release

on:
  push:
    tags:
      - 'v*' # Matches tags starting with 'v' (like v1.0.0, v2.3.4)

permissions:
  contents: write

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up variables
        id: set_vars
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"

          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "release_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set_vars.outputs.tag_name }}
          name: ${{ steps.set_vars.outputs.release_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
